#############################################
# iscsi-ha_local.conf
#
# This configuration file is for LOCAL OVERRIDE and customizations
# of the iscsi-ha setup. It allows you to modify specific settings
# in your iSCSI High Availability (HA) environment without changing
# the default configuration in the global iscsi-ha.conf.
#
# Example:
# To override the default replication IP address for the master node:
# SERVER_ONE_IP="192.168.1.100"
# To override the default SMTP SERVER address:
# SMTP_SERVER=mail.my_company.com
#
#############################################
C_MIN_RATE_SCALE_FACTOR="3"
LINK_SPEED_BYTES="167772160000000000"
REPLICATION_IP_ISCSI="10.10.10.3"
SERVER_ONE_IP="10.10.10.1"
SERVER_TWO_IP="10.10.10.2"
DISK_SPEED="157286400"
HEURISTIC_IP="4.4.4.4"
SERVER_ONE_NAME="mona"
SERVER_TWO_NAME="vhs"
REPLICATION_DEV_NAME="wlp54s0"
REPLICATION_SUBNET="10.10.10.0/24"
