#!/bin/bash

# TODO: looks like this script are not used anymore

# shellcheck source=/dev/null
# Source the configuration file for iscsi-ha
source /etc/iscsi-ha/iscsi-ha.load

# Initialize retry counter
RETRY=1

# Check if the host is in manual mode
if [ ! -e "$IHA_STATE_PATH/manual" ]; then
  echo "Host must be in manual mode for this operation."
  echo "Try 'iscsi-cfg manual-mode-enable'."
  exit 1
fi

echo "Waiting for peer to transition to secondary storage role"

# Loop until the peer becomes the primary storage role
while :; do
  echo -ne "Attempt [$RETRY] to become primary storage role with infinite attempts\r"

  # Attempt to become primary
  if /usr/bin/iscsi-cfg become-primary &>/dev/null; then
    # Check the status and break the loop if successful
    if /usr/bin/iscsi-cfg status; then
      break
    fi
  fi

  # Increment the retry counter
  RETRY=$((RETRY + 1))
  sleep 1
done
